// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs5gqHI-F4-40i4ewxsEED6-VO6rM0o38',
    appId: '1:128480933759:web:950aaa28ba39c8b3dccc4a',
    messagingSenderId: '128480933759',
    projectId: 'fir-series-d4105',
    authDomain: 'fir-series-d4105.firebaseapp.com',
    storageBucket: 'fir-series-d4105.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyS578vhuOxt9b6oT3IDxozzXHGG0c7zo',
    appId: '1:128480933759:android:e20c88dada79de23dccc4a',
    messagingSenderId: '128480933759',
    projectId: 'fir-series-d4105',
    storageBucket: 'fir-series-d4105.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHoQoueiDJOvjtybl8OmehM6U9U5s-dfg',
    appId: '1:128480933759:ios:7529d92ca1672db3dccc4a',
    messagingSenderId: '128480933759',
    projectId: 'fir-series-d4105',
    storageBucket: 'fir-series-d4105.appspot.com',
    iosBundleId: 'com.example.firebaseseries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHoQoueiDJOvjtybl8OmehM6U9U5s-dfg',
    appId: '1:128480933759:ios:7529d92ca1672db3dccc4a',
    messagingSenderId: '128480933759',
    projectId: 'fir-series-d4105',
    storageBucket: 'fir-series-d4105.appspot.com',
    iosBundleId: 'com.example.firebaseseries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs5gqHI-F4-40i4ewxsEED6-VO6rM0o38',
    appId: '1:128480933759:web:5921bceb43902c8ddccc4a',
    messagingSenderId: '128480933759',
    projectId: 'fir-series-d4105',
    authDomain: 'fir-series-d4105.firebaseapp.com',
    storageBucket: 'fir-series-d4105.appspot.com',
  );
}
